export const CHANGE_HOME_DATA = 'CHANGE_HOME_DATA'
export const STORE_ID_LIST = 'STORE_ID_LIST'

export const CHANGE_MOVIE_LIST = 'CHANGE_MOVIE_LIST'
export const CHANGE_CURRENT_MOVIE = 'CHANGE_CURRENT_MOVIE'
